# multicompartment_config.py
# Configuration for multi-compartment neuron models in Brian2Sim GUI

MULTICOMPARTMENT_CONFIG = {
    "enabled": {
        "type": "bool",
        "default": False,
        "description": "Enable multi-compartment neuron models",
        "tooltip": "Use detailed compartmental models instead of point neurons",
    },
    # Model architecture
    "model_type": {
        "type": "combo",
        "default": "ball_and_stick",
        "options": ["ball_and_stick", "branched_dendrites", "full_morphology", "custom"],
        "description": "Multi-compartment model architecture",
        "tooltip": "Choose the complexity level of compartmental structure",
        "depends_on": {"enabled": True},
    },
    "num_compartments": {
        "type": "int",
        "default": 3,
        "min": 2,
        "max": 50,
        "description": "Total number of compartments",
        "tooltip": "Total compartments (soma + dendrites + axon)",
        "depends_on": {"enabled": True},
    },
    # Soma configuration
    "soma_diameter": {
        "type": "float",
        "default": 20.0,
        "min": 5.0,
        "max": 50.0,
        "unit": "μm",
        "description": "Soma diameter",
        "tooltip": "Diameter of the cell body (pyramidal: 15-25 μm, interneuron: 10-20 μm)",
        "depends_on": {"enabled": True},
    },
    "soma_length": {
        "type": "float",
        "default": 20.0,
        "min": 5.0,
        "max": 50.0,
        "unit": "μm",
        "description": "Soma length",
        "tooltip": "Length of the soma compartment",
        "depends_on": {"enabled": True},
    },
    "soma_cm": {
        "type": "float",
        "default": 1.0,
        "min": 0.1,
        "max": 10.0,
        "unit": "μF/cm²",
        "description": "Soma membrane capacitance",
        "tooltip": "Specific membrane capacitance of soma",
        "depends_on": {"enabled": True},
    },
    "soma_rm": {
        "type": "float",
        "default": 10000.0,
        "min": 1000.0,
        "max": 100000.0,
        "unit": "Ω·cm²",
        "description": "Soma membrane resistance",
        "tooltip": "Specific membrane resistance of soma",
        "depends_on": {"enabled": True},
    },
    "soma_ra": {
        "type": "float",
        "default": 150.0,
        "min": 50.0,
        "max": 500.0,
        "unit": "Ω·cm",
        "description": "Soma axial resistance",
        "tooltip": "Intracellular resistance of soma",
        "depends_on": {"enabled": True},
    },
    # Dendritic configuration
    "dendrite_segments": {
        "type": "int",
        "default": 10,
        "min": 1,
        "max": 30,
        "description": "Number of dendritic segments",
        "tooltip": "Number of dendritic compartments",
        "depends_on": {"enabled": True},
    },
    "dendrite_diameter_proximal": {
        "type": "float",
        "default": 3.0,
        "min": 0.5,
        "max": 10.0,
        "unit": "μm",
        "description": "Proximal dendrite diameter",
        "tooltip": "Diameter at the base of dendrites",
        "depends_on": {"enabled": True},
    },
    "dendrite_diameter_distal": {
        "type": "float",
        "default": 0.5,
        "min": 0.1,
        "max": 5.0,
        "unit": "μm",
        "description": "Distal dendrite diameter",
        "tooltip": "Diameter at dendritic terminals",
    },
    "dendrite_length_total": {
        "type": "float",
        "default": 200.0,
        "min": 50.0,
        "max": 1000.0,
        "unit": "μm",
        "description": "Total dendritic length",
        "tooltip": "Combined length of all dendritic segments",
    },
    "dendrite_taper": {
        "type": "bool",
        "default": True,
        "description": "Enable dendritic tapering",
        "tooltip": "Gradually decrease diameter from proximal to distal",
    },
    "dendrite_branching": {
        "type": "bool",
        "default": False,
        "description": "Enable dendritic branching",
        "tooltip": "Create branched dendritic tree structure",
    },
    "branch_points": {
        "type": "int",
        "default": 2,
        "min": 0,
        "max": 5,
        "description": "Number of branch points",
        "tooltip": "Number of dendritic bifurcations",
    },
    "dendrite_cm": {
        "type": "float",
        "default": 1.0,
        "min": 0.1,
        "max": 10.0,
        "unit": "μF/cm²",
        "description": "Dendritic membrane capacitance",
        "tooltip": "Specific membrane capacitance of dendrites",
    },
    "dendrite_rm": {
        "type": "float",
        "default": 20000.0,
        "min": 5000.0,
        "max": 200000.0,
        "unit": "Ω·cm²",
        "description": "Dendritic membrane resistance",
        "tooltip": "Specific membrane resistance of dendrites",
    },
    "dendrite_ra": {
        "type": "float",
        "default": 200.0,
        "min": 100.0,
        "max": 1000.0,
        "unit": "Ω·cm",
        "description": "Dendritic axial resistance",
        "tooltip": "Intracellular resistance of dendrites",
    },
    # Axonal configuration
    "include_axon": {
        "type": "bool",
        "default": True,
        "description": "Include axonal compartment",
        "tooltip": "Add explicit axon initial segment and/or axon",
    },
    "axon_segments": {
        "type": "int",
        "default": 3,
        "min": 1,
        "max": 10,
        "description": "Number of axonal segments",
        "tooltip": "Number of axonal compartments",
    },
    "axon_diameter": {
        "type": "float",
        "default": 1.0,
        "min": 0.1,
        "max": 5.0,
        "unit": "μm",
        "description": "Axon diameter",
        "tooltip": "Diameter of axonal compartments",
    },
    "axon_length": {
        "type": "float",
        "default": 100.0,
        "min": 10.0,
        "max": 1000.0,
        "unit": "μm",
        "description": "Total axon length",
        "tooltip": "Combined length of axonal segments",
    },
    "ais_length": {
        "type": "float",
        "default": 25.0,
        "min": 10.0,
        "max": 50.0,
        "unit": "μm",
        "description": "Axon initial segment length",
        "tooltip": "Length of the axon initial segment (spike initiation zone)",
    },
    "axon_cm": {
        "type": "float",
        "default": 1.0,
        "min": 0.1,
        "max": 10.0,
        "unit": "μF/cm²",
        "description": "Axonal membrane capacitance",
        "tooltip": "Specific membrane capacitance of axon",
    },
    "axon_rm": {
        "type": "float",
        "default": 5000.0,
        "min": 1000.0,
        "max": 50000.0,
        "unit": "Ω·cm²",
        "description": "Axonal membrane resistance",
        "tooltip": "Specific membrane resistance of axon",
    },
    "axon_ra": {
        "type": "float",
        "default": 100.0,
        "min": 50.0,
        "max": 300.0,
        "unit": "Ω·cm",
        "description": "Axonal axial resistance",
        "tooltip": "Intracellular resistance of axon",
    },
    # Coupling configuration
    "coupling_conductance": {
        "type": "float",
        "default": 1e-6,
        "min": 1e-9,
        "max": 1e-3,
        "unit": "S",
        "description": "Inter-compartment coupling conductance",
        "tooltip": "Conductance between adjacent compartments",
    },
    "coupling_type": {
        "type": "combo",
        "default": "resistive",
        "options": ["resistive", "capacitive", "mixed"],
        "description": "Type of inter-compartment coupling",
        "tooltip": "How compartments are electrically connected",
    },
    # Ion channel distribution
    "channel_distribution": {
        "type": "bool",
        "default": True,
        "description": "Enable differential channel distribution",
        "tooltip": "Different ion channel densities in different compartments",
    },
    "soma_nav_density": {
        "type": "float",
        "default": 50.0,
        "min": 0.0,
        "max": 500.0,
        "unit": "mS/cm²",
        "description": "Soma Nav channel density",
        "tooltip": "Sodium channel density in soma",
    },
    "ais_nav_density": {
        "type": "float",
        "default": 200.0,
        "min": 50.0,
        "max": 1000.0,
        "unit": "mS/cm²",
        "description": "AIS Nav channel density",
        "tooltip": "Sodium channel density in axon initial segment",
    },
    "dendrite_nav_density": {
        "type": "float",
        "default": 10.0,
        "min": 0.0,
        "max": 100.0,
        "unit": "mS/cm²",
        "description": "Dendritic Nav channel density",
        "tooltip": "Sodium channel density in dendrites",
    },
    "soma_kv_density": {
        "type": "float",
        "default": 30.0,
        "min": 0.0,
        "max": 200.0,
        "unit": "mS/cm²",
        "description": "Soma Kv channel density",
        "tooltip": "Potassium channel density in soma",
    },
    "ais_kv_density": {
        "type": "float",
        "default": 100.0,
        "min": 10.0,
        "max": 500.0,
        "unit": "mS/cm²",
        "description": "AIS Kv channel density",
        "tooltip": "Potassium channel density in axon initial segment",
    },
    "dendrite_kv_density": {
        "type": "float",
        "default": 5.0,
        "min": 0.0,
        "max": 50.0,
        "unit": "mS/cm²",
        "description": "Dendritic Kv channel density",
        "tooltip": "Potassium channel density in dendrites",
    },
    "dendrite_ca_density": {
        "type": "float",
        "default": 0.5,
        "min": 0.0,
        "max": 10.0,
        "unit": "mS/cm²",
        "description": "Dendritic calcium channel density",
        "tooltip": "Calcium channel density in dendrites",
    },
    "dendrite_h_density": {
        "type": "float",
        "default": 0.1,
        "min": 0.0,
        "max": 2.0,
        "unit": "mS/cm²",
        "description": "Dendritic h-channel density",
        "tooltip": "HCN channel density in dendrites",
    },
    # Synaptic integration
    "synaptic_placement": {
        "type": "combo",
        "default": "dendritic_only",
        "options": ["soma_only", "dendritic_only", "distributed", "custom"],
        "description": "Where synapses are placed",
        "tooltip": "Spatial distribution of synaptic inputs",
    },
    "excitatory_dendrite_fraction": {
        "type": "float",
        "default": 0.9,
        "min": 0.1,
        "max": 1.0,
        "description": "Fraction of excitatory synapses on dendrites",
        "tooltip": "Proportion of excitatory synapses placed on dendrites vs soma",
    },
    "inhibitory_soma_fraction": {
        "type": "float",
        "default": 0.3,
        "min": 0.0,
        "max": 1.0,
        "description": "Fraction of inhibitory synapses on soma",
        "tooltip": "Proportion of inhibitory synapses placed on soma vs dendrites",
    },
    # Cable properties
    "cable_equation": {
        "type": "bool",
        "default": True,
        "description": "Use cable equation",
        "tooltip": "Solve full cable equation for realistic signal propagation",
    },
    "spatial_discretization": {
        "type": "float",
        "default": 10.0,
        "min": 1.0,
        "max": 50.0,
        "unit": "μm",
        "description": "Spatial discretization",
        "tooltip": "Maximum length of individual compartments",
    },
    "lambda_frequency": {
        "type": "float",
        "default": 100.0,
        "min": 1.0,
        "max": 1000.0,
        "unit": "Hz",
        "description": "Lambda frequency",
        "tooltip": "Frequency for calculating space constant",
    },
    # Morphology file options
    "morphology_file": {
        "type": "str",
        "default": "",
        "description": "Morphology file path",
        "tooltip": "Path to SWC or HOC morphology file (optional)",
    },
    "morphology_scale": {
        "type": "float",
        "default": 1.0,
        "min": 0.1,
        "max": 10.0,
        "description": "Morphology scaling factor",
        "tooltip": "Scale factor for imported morphology",
    },
    # Advanced options
    "temperature": {
        "type": "float",
        "default": 37.0,
        "min": 20.0,
        "max": 42.0,
        "unit": "°C",
        "description": "Temperature",
        "tooltip": "Temperature for kinetic rate corrections",
    },
    "q10_nav": {
        "type": "float",
        "default": 3.0,
        "min": 1.0,
        "max": 5.0,
        "description": "Q10 for Nav channels",
        "tooltip": "Temperature coefficient for sodium channels",
    },
    "q10_kv": {
        "type": "float",
        "default": 2.5,
        "min": 1.0,
        "max": 5.0,
        "description": "Q10 for Kv channels",
        "tooltip": "Temperature coefficient for potassium channels",
    },
    # Validation and research presets
    "cell_type_preset": {
        "type": "combo",
        "default": "custom",
        "options": [
            "custom",
            "L5_pyramidal",
            "L23_pyramidal",
            "fast_spiking_IN",
            "basket_cell",
            "chandelier_cell",
        ],
        "description": "Cell type preset",
        "tooltip": "Use research-validated parameters for specific cell types",
    },
    "brain_region": {
        "type": "combo",
        "default": "cortex",
        "options": ["cortex", "hippocampus", "cerebellum", "thalamus", "brainstem"],
        "description": "Brain region",
        "tooltip": "Optimize parameters for specific brain region",
    },
    "species": {
        "type": "combo",
        "default": "rat",
        "options": ["rat", "mouse", "human", "cat", "monkey"],
        "description": "Species",
        "tooltip": "Species-specific parameter scaling",
    },
    "developmental_stage": {
        "type": "combo",
        "default": "adult",
        "options": ["embryonic", "neonatal", "juvenile", "adult", "aged"],
        "description": "Developmental stage",
        "tooltip": "Age-appropriate morphological and electrical parameters",
    },
}
