# neuromodulation_config.py
# Configuration for neuromodulation systems in Brian2Sim GUI
# Neuromodulation affects neural activity through dopamine, acetylcholine, serotonin, etc.

NEUROMODULATION_CONFIG = {
    "enabled": {
        "type": "bool",
        "default": False,
        "label": "Enable Neuromodulation",
        "tooltip": "Enable neuromodulation systems (dopamine, acetylcholine, etc.)",
    },
    # Dopaminergic system
    "dopamine_system": {
        "type": "bool",
        "default": True,
        "label": "Dopamine System",
        "tooltip": "Enable dopaminergic neuromodulation",
        "depends_on": {"enabled": True},
    },
    "dopamine_baseline": {
        "type": "double",
        "default": 0.1,  # μM
        "min": 0.0,
        "max": 1.0,
        "decimals": 3,
        "suffix": " μM",
        "label": "Dopamine Baseline",
        "tooltip": "Baseline dopamine concentration (μM)",
        "depends_on": {"dopamine_system": True},
    },
    "dopamine_release_rate": {
        "type": "double",
        "default": 0.01,  # μM/ms
        "min": 0.0,
        "max": 0.1,
        "decimals": 4,
        "suffix": " μM/ms",
        "label": "Dopamine Release Rate",
        "tooltip": "Rate of dopamine release during reward (μM/ms)",
        "depends_on": {"dopamine_system": True},
    },
    "dopamine_clearance_tau": {
        "type": "double",
        "default": 1000.0,  # ms
        "min": 100.0,
        "max": 10000.0,
        "decimals": 1,
        "suffix": " ms",
        "label": "Dopamine Clearance Time",
        "tooltip": "Time constant for dopamine clearance (ms)",
        "depends_on": {"dopamine_system": True},
    },
    "dopamine_d1_effect": {
        "type": "double",
        "default": 0.2,
        "min": 0.0,
        "max": 2.0,
        "decimals": 2,
        "label": "D1 Receptor Effect",
        "tooltip": "Strength of D1 receptor-mediated effects",
        "depends_on": {"dopamine_system": True},
    },
    "dopamine_d2_effect": {
        "type": "double",
        "default": -0.15,
        "min": -2.0,
        "max": 0.0,
        "decimals": 2,
        "label": "D2 Receptor Effect",
        "tooltip": "Strength of D2 receptor-mediated effects (typically inhibitory)",
        "depends_on": {"dopamine_system": True},
    },
    # Cholinergic system
    "acetylcholine_system": {
        "type": "bool",
        "default": True,
        "label": "Acetylcholine System",
        "tooltip": "Enable cholinergic neuromodulation",
        "depends_on": {"enabled": True},
    },
    "acetylcholine_baseline": {
        "type": "double",
        "default": 0.05,  # μM
        "min": 0.0,
        "max": 0.5,
        "decimals": 3,
        "suffix": " μM",
        "label": "ACh Baseline",
        "tooltip": "Baseline acetylcholine concentration (μM)",
        "depends_on": {"acetylcholine_system": True},
    },
    "acetylcholine_release_rate": {
        "type": "double",
        "default": 0.005,  # μM/ms
        "min": 0.0,
        "max": 0.05,
        "decimals": 4,
        "suffix": " μM/ms",
        "label": "ACh Release Rate",
        "tooltip": "Rate of acetylcholine release (μM/ms)",
        "depends_on": {"acetylcholine_system": True},
    },
    "acetylcholine_clearance_tau": {
        "type": "double",
        "default": 200.0,  # ms
        "min": 50.0,
        "max": 2000.0,
        "decimals": 1,
        "suffix": " ms",
        "label": "ACh Clearance Time",
        "tooltip": "Time constant for acetylcholine clearance (ms)",
        "depends_on": {"acetylcholine_system": True},
    },
    "nicotinic_effect": {
        "type": "double",
        "default": 0.3,
        "min": 0.0,
        "max": 2.0,
        "decimals": 2,
        "label": "Nicotinic Receptor Effect",
        "tooltip": "Strength of nicotinic receptor-mediated effects",
        "depends_on": {"acetylcholine_system": True},
    },
    "muscarinic_effect": {
        "type": "double",
        "default": 0.15,
        "min": 0.0,
        "max": 1.0,
        "decimals": 2,
        "label": "Muscarinic Receptor Effect",
        "tooltip": "Strength of muscarinic receptor-mediated effects",
        "depends_on": {"acetylcholine_system": True},
    },
    # Serotonergic system
    "serotonin_system": {
        "type": "bool",
        "default": False,
        "label": "Serotonin System",
        "tooltip": "Enable serotonergic neuromodulation",
        "depends_on": {"enabled": True},
    },
    "serotonin_baseline": {
        "type": "double",
        "default": 0.02,  # μM
        "min": 0.0,
        "max": 0.2,
        "decimals": 3,
        "suffix": " μM",
        "label": "Serotonin Baseline",
        "tooltip": "Baseline serotonin concentration (μM)",
        "depends_on": {"serotonin_system": True},
    },
    "serotonin_release_rate": {
        "type": "double",
        "default": 0.002,  # μM/ms
        "min": 0.0,
        "max": 0.02,
        "decimals": 4,
        "suffix": " μM/ms",
        "label": "Serotonin Release Rate",
        "tooltip": "Rate of serotonin release (μM/ms)",
        "depends_on": {"serotonin_system": True},
    },
    "serotonin_clearance_tau": {
        "type": "double",
        "default": 500.0,  # ms
        "min": 100.0,
        "max": 5000.0,
        "decimals": 1,
        "suffix": " ms",
        "label": "Serotonin Clearance Time",
        "tooltip": "Time constant for serotonin clearance (ms)",
        "depends_on": {"serotonin_system": True},
    },
    "5ht1a_effect": {
        "type": "double",
        "default": -0.1,
        "min": -1.0,
        "max": 0.0,
        "decimals": 2,
        "label": "5-HT1A Receptor Effect",
        "tooltip": "Strength of 5-HT1A receptor-mediated effects (typically inhibitory)",
        "depends_on": {"serotonin_system": True},
    },
    "5ht2a_effect": {
        "type": "double",
        "default": 0.15,
        "min": 0.0,
        "max": 1.0,
        "decimals": 2,
        "label": "5-HT2A Receptor Effect",
        "tooltip": "Strength of 5-HT2A receptor-mediated effects",
        "depends_on": {"serotonin_system": True},
    },
    # Noradrenergic system
    "noradrenaline_system": {
        "type": "bool",
        "default": False,
        "label": "Noradrenaline System",
        "tooltip": "Enable noradrenergic neuromodulation",
        "depends_on": {"enabled": True},
    },
    "noradrenaline_baseline": {
        "type": "double",
        "default": 0.03,  # μM
        "min": 0.0,
        "max": 0.3,
        "decimals": 3,
        "suffix": " μM",
        "label": "Noradrenaline Baseline",
        "tooltip": "Baseline noradrenaline concentration (μM)",
        "depends_on": {"noradrenaline_system": True},
    },
    "noradrenaline_release_rate": {
        "type": "double",
        "default": 0.003,  # μM/ms
        "min": 0.0,
        "max": 0.03,
        "decimals": 4,
        "suffix": " μM/ms",
        "label": "Noradrenaline Release Rate",
        "tooltip": "Rate of noradrenaline release (μM/ms)",
        "depends_on": {"noradrenaline_system": True},
    },
    "noradrenaline_clearance_tau": {
        "type": "double",
        "default": 800.0,  # ms
        "min": 100.0,
        "max": 8000.0,
        "decimals": 1,
        "suffix": " ms",
        "label": "Noradrenaline Clearance Time",
        "tooltip": "Time constant for noradrenaline clearance (ms)",
        "depends_on": {"noradrenaline_system": True},
    },
    "alpha1_effect": {
        "type": "double",
        "default": 0.2,
        "min": 0.0,
        "max": 1.0,
        "decimals": 2,
        "label": "α1 Receptor Effect",
        "tooltip": "Strength of α1 adrenergic receptor effects",
        "depends_on": {"noradrenaline_system": True},
    },
    "alpha2_effect": {
        "type": "double",
        "default": -0.1,
        "min": -1.0,
        "max": 0.0,
        "decimals": 2,
        "label": "α2 Receptor Effect",
        "tooltip": "Strength of α2 adrenergic receptor effects (typically inhibitory)",
        "depends_on": {"noradrenaline_system": True},
    },
    "beta_effect": {
        "type": "double",
        "default": 0.15,
        "min": 0.0,
        "max": 1.0,
        "decimals": 2,
        "label": "β Receptor Effect",
        "tooltip": "Strength of β adrenergic receptor effects",
        "depends_on": {"noradrenaline_system": True},
    },
    # Release triggers and patterns
    "release_triggers": {
        "type": "combo",
        "default": "manual",
        "options": ["manual", "activity_dependent", "temporal_pattern", "reward_based"],
        "label": "Release Trigger",
        "tooltip": "What triggers neuromodulator release",
    },
    "activity_threshold": {
        "type": "double",
        "default": 20.0,  # Hz
        "min": 1.0,
        "max": 100.0,
        "decimals": 1,
        "suffix": " Hz",
        "label": "Activity Threshold",
        "tooltip": "Activity level that triggers neuromodulator release (Hz)",
    },
    "release_duration": {
        "type": "double",
        "default": 2000.0,  # ms
        "min": 100.0,
        "max": 10000.0,
        "decimals": 1,
        "suffix": " ms",
        "label": "Release Duration",
        "tooltip": "Duration of neuromodulator release events (ms)",
    },
    "release_interval": {
        "type": "double",
        "default": 10000.0,  # ms
        "min": 1000.0,
        "max": 60000.0,
        "decimals": 1,
        "suffix": " ms",
        "label": "Release Interval",
        "tooltip": "Interval between release events (ms)",
    },
    # Effects on neural properties
    "affect_excitability": {
        "type": "bool",
        "default": True,
        "label": "Affect Neural Excitability",
        "tooltip": "Neuromodulators affect intrinsic excitability",
    },
    "affect_synaptic_transmission": {
        "type": "bool",
        "default": True,
        "label": "Affect Synaptic Transmission",
        "tooltip": "Neuromodulators affect synaptic strength",
    },
    "affect_plasticity": {
        "type": "bool",
        "default": True,
        "label": "Affect Plasticity",
        "tooltip": "Neuromodulators modulate synaptic plasticity",
    },
    "affect_gap_junctions": {
        "type": "bool",
        "default": False,
        "label": "Affect Gap Junctions",
        "tooltip": "Neuromodulators affect gap junction coupling",
    },
    # Spatial distribution
    "spatial_distribution": {
        "type": "combo",
        "default": "uniform",
        "options": ["uniform", "gradient", "localized", "patchy"],
        "label": "Spatial Distribution",
        "tooltip": "Spatial pattern of neuromodulator effects",
    },
    "gradient_direction": {
        "type": "combo",
        "default": "anterior_posterior",
        "options": ["anterior_posterior", "dorsal_ventral", "medial_lateral", "center_periphery"],
        "label": "Gradient Direction",
        "tooltip": "Direction of concentration gradient",
    },
    "gradient_strength": {
        "type": "double",
        "default": 0.5,
        "min": 0.0,
        "max": 1.0,
        "decimals": 2,
        "label": "Gradient Strength",
        "tooltip": "Strength of spatial concentration gradient",
    },
    # Receptor desensitization
    "receptor_desensitization": {
        "type": "bool",
        "default": False,
        "label": "Receptor Desensitization",
        "tooltip": "Enable receptor desensitization with prolonged exposure",
    },
    "desensitization_tau": {
        "type": "double",
        "default": 5000.0,  # ms
        "min": 1000.0,
        "max": 30000.0,
        "decimals": 1,
        "suffix": " ms",
        "label": "Desensitization Time Constant",
        "tooltip": "Time constant for receptor desensitization (ms)",
    },
    "desensitization_strength": {
        "type": "double",
        "default": 0.7,
        "min": 0.1,
        "max": 1.0,
        "decimals": 2,
        "label": "Desensitization Strength",
        "tooltip": "Fraction of receptors that desensitize",
    },
    # Pharmacological interventions
    "pharmacology": {
        "type": "bool",
        "default": False,
        "label": "Pharmacological Interventions",
        "tooltip": "Simulate drug effects on neuromodulation",
    },
    "drug_type": {
        "type": "combo",
        "default": "dopamine_agonist",
        "options": [
            "dopamine_agonist",
            "dopamine_antagonist",
            "acetylcholine_agonist",
            "acetylcholine_antagonist",
            "serotonin_agonist",
            "serotonin_antagonist",
            "noradrenaline_agonist",
            "noradrenaline_antagonist",
        ],
        "label": "Drug Type",
        "tooltip": "Type of pharmacological intervention",
    },
    "drug_concentration": {
        "type": "double",
        "default": 0.1,  # μM
        "min": 0.0,
        "max": 10.0,
        "decimals": 3,
        "suffix": " μM",
        "label": "Drug Concentration",
        "tooltip": "Concentration of administered drug (μM)",
    },
    "drug_onset_time": {
        "type": "double",
        "default": 10000.0,  # ms
        "min": 0.0,
        "max": 100000.0,
        "decimals": 1,
        "suffix": " ms",
        "label": "Drug Onset Time",
        "tooltip": "Time when drug administration begins (ms)",
    },
    "drug_duration": {
        "type": "double",
        "default": 30000.0,  # ms
        "min": 1000.0,
        "max": 200000.0,
        "decimals": 1,
        "suffix": " ms",
        "label": "Drug Duration",
        "tooltip": "Duration of drug effect (ms)",
    },
    # Advanced features
    "cotransmission": {
        "type": "bool",
        "default": False,
        "label": "Cotransmission",
        "tooltip": "Enable co-release of multiple neuromodulators",
    },
    "volume_transmission": {
        "type": "bool",
        "default": True,
        "label": "Volume Transmission",
        "tooltip": "Enable volume transmission (diffuse signaling)",
    },
    "diffusion_coefficient": {
        "type": "double",
        "default": 0.1,  # μm²/ms
        "min": 0.01,
        "max": 1.0,
        "decimals": 3,
        "suffix": " μm²/ms",
        "label": "Diffusion Coefficient",
        "tooltip": "Diffusion coefficient for volume transmission",
    },
    "membrane_permeability": {
        "type": "double",
        "default": 0.01,  # cm/s
        "min": 0.001,
        "max": 0.1,
        "decimals": 4,
        "suffix": " cm/s",
        "label": "Membrane Permeability",
        "tooltip": "Membrane permeability to neuromodulators",
    },
}

# Neuromodulation research references and validation ranges (2025 standards)
NEUROMODULATION_RESEARCH_INFO = {
    "description": "Neuromodulation systems regulate neural activity and plasticity through diffuse release of dopamine, acetylcholine, serotonin, and noradrenaline.",
    "physiological_ranges": {
        "dopamine_concentration": {
            "range": "0.01-1.0 μM",
            "typical": "0.05-0.2 μM",
            "notes": "Varies greatly by brain region and behavioral state",
        },
        "acetylcholine_concentration": {
            "range": "0.005-0.5 μM",
            "typical": "0.02-0.1 μM",
            "notes": "Higher in attention and learning states",
        },
        "serotonin_concentration": {
            "range": "0.001-0.2 μM",
            "typical": "0.01-0.05 μM",
            "notes": "Modulates mood and arousal states",
        },
    },
    "research_references": [
        "Schultz (2016) Dopamine reward prediction error coding. Dialogues Clin Neurosci 18:23-32",
        "Hasselmo & Sarter (2011) Modes and models of forebrain cholinergic neuromodulation of cognition. Neuropsychopharmacology 36:52-73",
        "Dayan & Huys (2009) Serotonin in affective control. Annu Rev Neurosci 32:95-126",
        "Sara (2009) The locus coeruleus and noradrenergic modulation of cognition. Nat Rev Neurosci 10:211-223",
        "Nadim & Bucher (2014) Neuromodulation of neurons and synapses. Curr Opin Neurobiol 29:48-56",
        "Bargmann (2012) Beyond the connectome: how neuromodulators shape neural circuits. Bioessays 34:458-465",
    ],
    "implementation_notes": {
        "brian2_syntax": "Use TimedArray for concentration profiles and differential equations for receptor dynamics",
        "computational_efficiency": "Neuromodulator diffusion can be computationally expensive - use simplified models",
        "validation_tests": "Test dose-response curves, temporal dynamics, and behavioral effects",
        "network_effects": "Neuromodulation can dramatically alter network dynamics and oscillations",
    },
    "disease_associations": {
        "parkinsons_disease": "Loss of dopaminergic neurons in substantia nigra",
        "alzheimers_disease": "Cholinergic neuron degeneration and reduced ACh",
        "depression": "Altered serotonin and noradrenaline signaling",
        "schizophrenia": "Dopaminergic and cholinergic dysfunction",
        "adhd": "Altered dopamine and noradrenaline function",
        "addiction": "Dysregulated dopamine reward pathways",
    },
}
