"""
Code Generator for Brian2 neural network simulator.
Generates standalone Python scripts from GUI parameters.
"""

from datetime import datetime


class CodeGenerator:
    """Generator for standalone Brian2 simulation code."""

    def __init__(self):
        pass

    def generate_simulation_code(self, params):
        """Generate a complete Brian2 simulation script from parameters."""
        code_lines = []

        # Header and imports
        code_lines.extend(self._generate_header())
        code_lines.extend(self._generate_imports())

        # Main simulation function
        code_lines.extend(self._generate_main_function(params))

        # Helper functions
        code_lines.extend(self._generate_helper_functions(params))

        # Main execution
        code_lines.extend(self._generate_main_execution())

        return "\n".join(code_lines)

    def _generate_header(self):
        """Generate file header with timestamp and description."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return [
            f'"""',
            f"Brian2 Neural Network Simulation",
            f"Generated by brian2sim-gui on {timestamp}",
            f"",
            f"This script reproduces the simulation configured in the GUI.",
            f"Make sure you have Brian2 installed: pip install brian2",
            f'"""',
            f"",
        ]

    def _generate_imports(self):
        """Generate import statements."""
        return [
            "# Import required libraries",
            "from brian2 import *",
            "import matplotlib.pyplot as plt",
            "import numpy as np",
            "from datetime import datetime",
            "",
        ]

    def _generate_main_function(self, params):
        """Generate the main simulation function."""
        lines = [
            "def run_simulation():",
            '    """Run the neural network simulation."""',
            '    print("Starting Brian2 simulation...")',
            "    ",
            "    # Clear any previous Brian2 objects",
            "    start_scope()",
            "    ",
        ]
        # Extract parameters
        sim_params = params.get("simulation", {})
        neuron_params = params.get("neuron_model", {})
        noise_params = params.get("noise", {})
        network_params = params.get("network", {})
        advanced_params = params.get("advanced_network", {})
        
        # Advanced features
        synaptic_receptors_params = params.get("synaptic_receptors", {})
        short_term_plasticity_params = params.get("short_term_plasticity", {})
        calcium_dynamics_params = params.get("calcium_dynamics", {})
        homeostatic_params = params.get("homeostatic_plasticity", {})
        neuromodulation_params = params.get("neuromodulation", {})
        multicompartment_params = params.get("multicompartment", {})

        # Add parameter comments
        lines.extend(self._generate_parameter_comments(params))

        # Build neurons
        # Check if multicompartment
        if multicompartment_params.get("enabled", False):
            lines.extend(self._generate_multicompartment_code(sim_params, multicompartment_params, neuron_params, calcium_dynamics_params))
        else:
            lines.extend(self._generate_neuron_code(sim_params, neuron_params))

        # Add input current
        lines.extend(self._generate_input_current_code(sim_params))

        # Add noise if enabled
        if noise_params.get("enabled", False):
            lines.extend(self._generate_noise_code(noise_params))
            
        # Add input patterns
        if params.get("input_patterns"):
            lines.extend(self._generate_input_patterns_code(params.get("input_patterns")))

        # Add network connections if enabled
        # Covers simple synapes, receptors, and STP
        if network_params.get("enabled", False) or network_params.get("synaptic_connections", False):
            lines.extend(self._generate_synapses_code(
                network_params, 
                advanced_params, 
                synaptic_receptors_params, 
                short_term_plasticity_params, 
                calcium_dynamics_params,
                sim_params
            ))

        # Add gap junctions
        lines.extend(self._generate_gap_junctions_code(params))
        
        # Add plasticity (Homeostasis & Neuromodulation)
        lines.extend(self._generate_plasticity_code(homeostatic_params, neuromodulation_params))

        # Setup monitors
        lines.extend(self._generate_monitors_code(sim_params))

        # Run simulation
        lines.extend(self._generate_run_code(sim_params))

        # Analyze results
        lines.extend(self._generate_analysis_code())

        # Plot results
        lines.extend(self._generate_plotting_code())

        return lines

    def _generate_parameter_comments(self, params):
        """Generate comments documenting the parameters."""
        lines = ["    # Simulation Parameters:"]

        sim_params = params.get("simulation", {})
        for key, value in sim_params.items():
            lines.append(f"    # {key}: {value}")

        neuron_params = params.get("neuron_model", {})
        if neuron_params:
            lines.append("    # Neuron Model:")
            for key, value in neuron_params.items():
                lines.append(f"    # {key}: {value}")

        lines.append("    ")
        return lines

    def _generate_neuron_code(self, sim_params, neuron_params):
        """Generate neuron group creation code."""
        lines = ["    # Create neuron group"]

        num_neurons = sim_params.get("num_neurons", 1)
        model_type = neuron_params.get("model_key", "lif")
        
        # Support nested parameters check
        params = neuron_params.get("parameters", neuron_params)

        if model_type == "lif":
            threshold = sim_params.get("v_threshold", -50)
            reset = sim_params.get("v_reset", -70)
            tau = params.get("tau_m", 20)
            v_rest = params.get("v_rest", -70)
            resistance = params.get("resistance", 100)
            refractory = params.get("refractory", 2.0)

            lines.extend(
                [
                    f"    tau_m = {tau} * ms",
                    f"    R = {resistance} * Mohm",
                    f"    v_threshold = {threshold} * mV",
                    f"    v_reset = {reset} * mV",
                    f"    v_rest = {v_rest} * mV",
                    f"    refractory_period = {refractory} * ms",
                    "    ",
                    '    neuron_eqs = """',
                    "    dv/dt = (-(v - v_rest) + R * (I + I_gap)) / tau_m : volt (unless refractory)",
                    "    I : amp",
                    "    I_gap : amp",
                    "    activity : Hz  # For plasticity",
                    '    """',
                    "    ",
                    f"    neurons = NeuronGroup({num_neurons}, neuron_eqs,",
                    '                          threshold="v > v_threshold",',
                    '                          reset="v = v_reset; activity += 1*Hz",',
                    "                          refractory=refractory_period,",
                    '                          method="euler")',
                    "    neurons.v = v_reset",
                    "    neurons.I_gap = 0 * amp",
                    "    ",
                ]
            )

        elif model_type == "lif_coba":
            # Conductance-Based LIF
            Cm = params.get("Cm", 200)
            gl = params.get("gl", 10)
            El = params.get("El", -60)
            threshold = params.get("v_threshold", -50)
            reset = params.get("v_reset", -60)
            refractory = params.get("refractory", 5.0)
            
            Ee = params.get("Ee", 0)
            Ei = params.get("Ei", -80)
            taue = params.get("taue", 5.0)
            taui = params.get("taui", 10.0)

            lines.extend(
                [
                    f"    Cm = {Cm} * pF",
                    f"    gl = {gl} * nS",
                    f"    El = {El} * mV",
                    f"    v_threshold = {threshold} * mV",
                    f"    v_reset = {reset} * mV",
                    f"    refractory_period = {refractory} * ms",
                    f"    Ee = {Ee} * mV",
                    f"    Ei = {Ei} * mV",
                    f"    taue = {taue} * ms",
                    f"    taui = {taui} * ms",
                    "    ",
                    '    neuron_eqs = """',
                    "    dv/dt = (gl * (El - v) + ge * (Ee - v) + gi * (Ei - v) + I) / Cm : volt (unless refractory)",
                    "    dge/dt = -ge / taue : siemens",
                    "    dgi/dt = -gi / taui : siemens",
                    "    I : amp",
                    '    """',
                    "    ",
                    f"    neurons = NeuronGroup({num_neurons}, neuron_eqs,",
                    '                          threshold="v > v_threshold",',
                    '                          reset="v = v_reset",',
                    "                          refractory=refractory_period,",
                    '                          method="euler")',
                    "    neurons.v = v_reset",
                    # Initialize conductances to 0
                    "    neurons.ge = 0 * nS",
                    "    neurons.gi = 0 * nS",
                    "    neurons.I = 0 * amp",
                    "    ",
                ]
            )

        elif model_type == "izhikevich":
            parameters = neuron_params.get("parameters", {})
            a = parameters.get("a", 0.02)
            b = parameters.get("b", 0.2)
            c = parameters.get("c", -65)
            d = parameters.get("d", 8)

            lines.extend(
                [
                    f"    a = {a}",
                    f"    b = {b}",
                    f"    c = {c}",
                    f"    d = {d}",
                    "    ",
                    '    neuron_eqs = """',
                    "    dv/dt = (0.04*v**2 + 5*v + 140 - u + I + I_gap)/ms : 1",
                    "    du/dt = (a*(b*v - u))/ms : 1",
                    "    I : 1",
                    "    I_gap : 1",
                    '    """',
                    "    ",
                    f"    neurons = NeuronGroup({num_neurons}, neuron_eqs,",
                    '                          threshold="v >= 30",',
                    '                          reset="v = c; u += d",',
                    '                          method="euler")',
                    f"    neurons.v = {c}",
                    f"    neurons.u = {b} * {c}",
                    "    neurons.I_gap = 0",
                    "    ",
                ]
            )

        elif model_type == "adex":
            # Adaptive Exponential Integrate-and-Fire (AdEx)
            parameters = neuron_params.get("parameters", {})
            C = parameters.get("C", 200)
            gL = parameters.get("gL", 10)
            EL = parameters.get("EL", -70)
            VT = parameters.get("VT", -50)
            delT = parameters.get("delT", 2)
            a_param = parameters.get("a", 2)
            tauw = parameters.get("tauw", 30)
            b_param = parameters.get("b", 60)
            
            # v_reset from sim_params or default to EL
            vr_val = sim_params.get("v_reset", EL)

            lines.extend(
                [
                    f"    C = {C} * pF",
                    f"    gL = {gL} * nS",
                    f"    EL = {EL} * mV",
                    f"    VT = {VT} * mV",
                    f"    delT = {delT} * mV",
                    f"    a = {a_param} * nS",
                    f"    tauw = {tauw} * ms",
                    f"    b = {b_param} * pA",
                    f"    v_reset = {vr_val} * mV",
                    "    ",
                    '    neuron_eqs = """',
                    "    dv/dt = (gL*(EL - v) + gL*delT*exp((v - VT)/delT) - w + I + I_gap)/C : volt",
                    "    dw/dt = (a*(v - EL) - w)/tauw : amp",
                    "    I : amp",
                    "    I_gap : amp",
                    '    """',
                    "    ",
                    f"    neurons = NeuronGroup({num_neurons}, neuron_eqs,",
                    '                          threshold="v > VT + 5*delT",',
                    '                          reset="v = v_reset; w += b",',
                    '                          method="euler")',
                    "    neurons.v = EL",
                    "    neurons.w = 0 * pA",
                    "    neurons.I_gap = 0 * amp",
                    "    ",
                ]
            )
        else:
            # Default to simple LIF
            lines.extend(
                [
                    "    # Default LIF model",
                    '    neuron_eqs = """',
                    "    dv/dt = (-v + R*I)/tau : volt",
                    "    I : amp",
                    "    I_gap : amp",
                    '    """',
                    f"    neurons = NeuronGroup({num_neurons}, neuron_eqs,",
                    '                          threshold="v > -50*mV",',
                    '                          reset="v = -70*mV",',
                    '                          method="euler")',
                    "    neurons.v = -70 * mV",
                    "    ",
                ]
            )

        return lines

    def _generate_input_current_code(self, sim_params):
        """Generate input current code."""
        current_amplitude = sim_params.get("input_current", 0.5)
        current_start = sim_params.get("current_start", 10)
        current_duration = sim_params.get("current_duration", 50)

        return [
            "    # Setup input current",
            f"    I_amplitude = {current_amplitude} * nA",
            f"    I_start = {current_start} * ms",
            f"    I_duration = {current_duration} * ms",
            "    ",
            "    @network_operation(dt=0.1*ms)",
            "    def input_current():",
            "        if I_start <= defaultclock.t < I_start + I_duration:",
            "            neurons.I = I_amplitude",
            "        else:",
            "            neurons.I = 0*nA",
            "    ",
        ]

    def _generate_noise_code(self, noise_params):
        """Generate noise code."""
        intensity = noise_params.get("intensity", 0.1)
        method = noise_params.get("method", "Gaussian")

        lines = [
            "    # Add noise",
            f"    noise_intensity = {intensity} * nA",
        ]

        if method == "Gaussian":
            lines.extend(
                [
                    "    ",
                    "    @network_operation(dt=0.1*ms)",
                    "    def add_noise():",
                    "        neurons.I += noise_intensity * randn(len(neurons))",
                    "    ",
                ]
            )
        elif method == "Ornstein-Uhlenbeck":
            lines.extend(
                [
                    "    # Note: Simplified O-U noise implementation",
                    "    tau_noise = 5 * ms",
                    '    noise_eqs = "dI_noise/dt = -I_noise/tau_noise + sigma*sqrt(2/tau_noise)*xi : amp"',
                    "    # This would require modifying the neuron equations",
                    "    ",
                ]
            )
            return lines

    def _generate_synapses_code(self, network_params, advanced_params, receptors_params, stp_params, ca_params, sim_params):
        """Generate synaptic connection code, supporting advanced features."""
        lines = ["    # Synaptic connections"]
        
        use_receptors = receptors_params.get("enabled", False)
        use_stp = stp_params.get("enabled", False)
        stdp_params = advanced_params.get("stdp", {})
        use_stdp = stdp_params.get("enabled", False)

        if not (use_receptors or use_stp or use_stdp):
            # --- SIMPLE SYNAPSES ---
            weight = network_params.get("weight", 0.5)
            use_reversals = advanced_params and ("exc_reversal" in advanced_params or "inh_reversal" in advanced_params)
            
            if use_reversals:
                v_norm = advanced_params.get("driving_force_norm", 70.0)
                exc_rev = advanced_params.get("exc_reversal", 0.0)
                inh_rev = advanced_params.get("inh_reversal", -80.0)
                
                lines.extend([
                    f"    v_norm = {v_norm} * mV",
                    '    syn_model = """',
                    "    w : siemens",
                    "    E_rev : volt",
                    '    """',
                    '    syn_on_pre = "v_post += (w/nS) * ((E_rev - v_post) / v_norm) * mV"',
                    "    synapses = Synapses(neurons, neurons, model=syn_model, on_pre=syn_on_pre)",
                    f"    synapses.w = {weight} * nS",
                    f"    synapses.E_rev = {exc_rev} * mV  # Default to excitatory",
                ])
            else:
                lines.extend([
                    f"    w_syn = {weight} * nS",
                    '    synapses = Synapses(neurons, neurons, "w : siemens", on_pre="v_post += w/nS * mV")',
                    "    synapses.w = w_syn",
                ])
                
        else:
            # --- ADVANCED SYNAPSES (Receptors, STP, STDP) ---
            model_parts = ["w : siemens"]
            on_pre_parts = []
            on_post_parts = []
            
            # 1. Receptors
            if use_receptors:
                if receptors_params.get("ampa_enabled"):
                    tau = receptors_params.get("ampa_tau_decay", 2.0)
                    rev = receptors_params.get("ampa_reversal", 0.0)
                    ratio = receptors_params.get("ampa_weight_ratio", 1.0)
                    lines.append(f"    tau_ampa = {tau}*ms; E_ampa = {rev}*mV; w_ampa_R = {ratio}")
                    model_parts.append("dg_ampa/dt = -g_ampa / tau_ampa : siemens")
                    model_parts.append("I_ampa = g_ampa * (E_ampa - v_post) : amp")
                    on_pre_parts.append("g_ampa += w * w_ampa_R")

                if receptors_params.get("nmda_enabled"):
                    tau_r = receptors_params.get("nmda_tau_rise", 2.0)
                    tau_d = receptors_params.get("nmda_tau_decay", 100.0)
                    rev = receptors_params.get("nmda_reversal", 0.0)
                    mg = receptors_params.get("nmda_mg_concentration", 1.0)
                    ratio = receptors_params.get("nmda_weight_ratio", 0.5)
                    lines.append(f"    tau_nmda_r={tau_r}*ms; tau_nmda_d={tau_d}*ms; E_nmda={rev}*mV; mg={mg}; w_nmda_R={ratio}")
                    model_parts.append("dg_nmda/dt = (s_nmda - g_nmda)/tau_nmda_d : siemens")
                    model_parts.append("ds_nmda/dt = -s_nmda/tau_nmda_r : siemens")
                    model_parts.append("B_mg = 1.0 / (1.0 + (mg/3.57) * exp(-0.062 * v_post/mV)) : 1")
                    model_parts.append("I_nmda = g_nmda * B_mg * (E_nmda - v_post) : amp")
                    on_pre_parts.append("s_nmda += w * w_nmda_R")

                if receptors_params.get("gaba_a_enabled"):
                    tau_r = receptors_params.get("gaba_a_tau_rise", 0.5)
                    tau_d = receptors_params.get("gaba_a_tau_decay", 6.0)
                    rev = receptors_params.get("gaba_a_reversal", -70.0)
                    ratio = receptors_params.get("gaba_a_weight_ratio", 1.5)
                    lines.append(f"    tau_gaba_a_r={tau_r}*ms; tau_gaba_a_d={tau_d}*ms; E_gaba_a={rev}*mV; w_gaba_a_R={ratio}")
                    model_parts.append("dg_gaba_a/dt = (s_gaba_a - g_gaba_a)/tau_gaba_a_d : siemens")
                    model_parts.append("ds_gaba_a/dt = -s_gaba_a/tau_gaba_a_r : siemens")
                    model_parts.append("I_gaba_a = g_gaba_a * (E_gaba_a - v_post) : amp")
                    on_pre_parts.append("s_gaba_a += w * w_gaba_a_R")

                if receptors_params.get("gaba_b_enabled"):
                    tau_r = receptors_params.get("gaba_b_tau_rise", 50.0)
                    tau_d = receptors_params.get("gaba_b_tau_decay", 200.0)
                    rev = receptors_params.get("gaba_b_reversal", -90.0)
                    ratio = receptors_params.get("gaba_b_weight_ratio", 0.5)
                    lines.append(f"    tau_gaba_b_r={tau_r}*ms; tau_gaba_b_d={tau_d}*ms; E_gaba_b={rev}*mV; w_gaba_b_R={ratio}")
                    model_parts.append("dg_gaba_b/dt = (s_gaba_b - g_gaba_b)/tau_gaba_b_d : siemens")
                    model_parts.append("ds_gaba_b/dt = -s_gaba_b/tau_gaba_b_r : siemens")
                    model_parts.append("I_gaba_b = g_gaba_b * (E_gaba_b - v_post) : amp")
                    on_pre_parts.append("s_gaba_b += w * w_gaba_b_R")
                
                # Sum inputs into I_post (targeting neurons.I)
                currents = [f"I_{x}" for x in ["ampa","nmda","gaba_a","gaba_b"] if receptors_params.get(f"{x}_enabled")]
                if currents:
                    model_parts.append(f"I_syn = {' + '.join(currents)} : amp")
                    model_parts.append("I_post = I_syn : amp (summed)")

            # 2. STP
            if use_stp:
                 U = stp_params.get("tm_U", 0.5)
                 tau_d = stp_params.get("tm_tau_d", 800.0)
                 tau_f = stp_params.get("tm_tau_f", 50.0)
                 lines.extend([f"    tau_stp_d={tau_d}*ms; tau_stp_f={tau_f}*ms; U_stp={U}"])
                 model_parts.append("dx/dt = (1 - x)/tau_stp_d : 1 (event-driven)")
                 model_parts.append("du/dt = (U_stp - u)/tau_stp_f : 1 (event-driven)")
                 model_parts.append("r : 1") 
                 stp_pre = "u += U_stp * (1 - u); r = u * x; x -= r; "
                 on_pre_parts.insert(0, stp_pre)
                 on_pre_parts = [p.replace("w *", "w * r *") if "w *" in p else p for p in on_pre_parts]

            # 3. STDP
            if use_stdp:
                 lines.append(f"    tau_pre=20*ms; tau_post=20*ms; A_plus=0.01; A_minus=0.0105; w_max=1.0*nS")
                 model_parts.append("dapre/dt = -apre/tau_pre : 1 (event-driven)")
                 model_parts.append("dapost/dt = -apost/tau_post : 1 (event-driven)")
                 on_pre_parts.append("apre += A_plus; w = clip(w + apost, 0, w_max)")
                 on_post_parts.append("apost -= A_minus; w = clip(w + apre, 0, w_max)")

            eqs_str = "\\n            ".join(model_parts)
            pre_str = "; ".join(on_pre_parts)
            post_str = "; ".join(on_post_parts)

            lines.extend([
                '    syn_model = """',
                f'    {eqs_str}',
                '    """',
                f'    syn_on_pre = "{pre_str}"',
                f'    syn_on_post = "{post_str}"',
                "    synapses = Synapses(neurons, neurons, model=syn_model, on_pre=syn_on_pre, on_post=syn_on_post)",
                "    synapses.w = 0.5 * nS",
            ])
            
            if use_stp:
                 lines.append("    synapses.x = 1.0; synapses.u = U_stp")

        # Topology
        topology = network_params.get("network_topology", "random")
        lines.append(f"    # Topology: {topology}")
        params = self._extract_topology_params(network_params, advanced_params)
        
        if topology == "random":
             lines.append(f"    synapses.connect(p=params['connection_probability'])")
        elif topology == "all_to_all":
             lines.append("    synapses.connect(condition='i != j')")
        else:
             lines.append(f"    synapses.connect(p=params['connection_probability'])")

        lines.append("    ")
        return lines

    def _extract_topology_params(self, network_params, advanced_params):
        return {
            "connection_probability": network_params.get("connection_probability", 0.1),
            "allow_self_connections": network_params.get("allow_self_connections", False),
        }

    def _generate_plasticity_code(self, homeo_params, neuro_params):
        """Generate plasticity code."""
        lines = ["    # Plasticity"]
        if homeo_params.get("enabled", False):
            lines.append("    # Homeostatic Mechanisms (Activity & Scaling)")
            
            if homeo_params.get("activity_detection", True):
                lines.append(f"    tau_act = {homeo_params.get('tau_activity', 1000.0)}*ms")
                lines.append(f"    target = {homeo_params.get('target_rate', 5.0)}*Hz")
                lines.append('    neurons.run_regularly("activity = activity * exp(-dt/tau_act); activity_error = activity - target", dt=10*ms)')
                
            if homeo_params.get("synaptic_scaling", False):
                lines.append("    # Synaptic Scaling")
                lines.append('    if "synapses" in locals():')
                lines.append('        synapses.run_regularly("scaling_factor = 1 + 0.001 * (target - activity_post)/Hz; w = clip(w * scaling_factor, 0, 100*nS)", dt=100*ms)')

        return lines

    def _generate_input_patterns_code(self, input_params):
        """Generate input patterns code."""
        return ["    # Input patterns not fully implemented in generation"]

    def _generate_multicompartment_code(self, sim_params, multicomp_params, neuron_params, ca_params):
        """Generate multicompartment code (Fallback)."""
        lines = ["    # Multicompartment model (Fallback to Point Neuron)"]
        lines.append('    print("Warning: SpatialNeuron code generation not supported. Using Point Neurons.")')
        lines.extend(self._generate_neuron_code(sim_params, neuron_params))
        return lines

    def _generate_gap_junctions_code(self, params):
        """Generate gap junctions code."""
        gap_params = params.get("gap_junctions", {})
        if not gap_params.get("enabled", False):
            return []

        lines = ["    # Gap Junctions"]
        
        conductance = gap_params.get("conductance", 0.1)
        gj_type = gap_params.get("junction_type", "symmetric")
        voltage_dep = gap_params.get("voltage_dependence", False)
        
        lines.append(f"    g_gap_conductance = {conductance} * nS")
        
        # Build model equations string
        eqs = ["g_gap : siemens"]
        g_eff_str = "g_gap"
        
        if voltage_dep:
            v_half = gap_params.get("gating_voltage", -40.0)
            slope = gap_params.get("gating_slope", 10.0)
            eqs.append(f"g_open = 1 / (1 + exp(-(v_pre - v_post - ({v_half}*mV)) / ({slope}*mV))) : 1")
            g_eff_str += " * g_open"
            
        if gj_type == "rectifying":
            eqs.append("ratio = int(v_pre > v_post) : 1")
            g_eff_str += " * ratio"
            
        eqs.append(f"g_effective = {g_eff_str} : siemens")
        eqs.append("I_gap_post = g_effective * (v_pre - v_post) : amp (summed)")
        
        eqs_str = "\\n            ".join(eqs)
        
        lines.extend([
            f'    gap_model = """',
            f'    {eqs_str}',
            f'    """',
            "    gap_junctions = Synapses(neurons, neurons, model=gap_model, method='euler')",
            "    gap_junctions.g_gap = g_gap_conductance",
            "    ",
        ])
        
        # Connectivity
        pattern = gap_params.get("spatial_organization", "random")
        if pattern == "random":
            prob = gap_params.get("connection_probability", 0.05)
            lines.append(f"    gap_junctions.connect(condition='i < j', p={prob})")
            lines.append(f"    gap_junctions.connect(condition='i > j', p={prob})")
            lines.append("    # Note: Bidirectional random connections created")
            
        elif pattern == "nearest_neighbor":
            k = gap_params.get("num_neighbors", 2)
            lines.append(f"    # Nearest neighbor connectivity (k={k})")
            lines.append("    for i in range(len(neurons)):")
            lines.append(f"        for j in range(1, {k} + 1):")
            lines.append("            if i + j < len(neurons):")
            lines.append("                gap_junctions.connect(i=i, j=i+j)")
            lines.append("                gap_junctions.connect(i=i+j, j=i)")
            
        else:
            # Fallback
            lines.append("    gap_junctions.connect(condition='i != j', p=0.01) # Fallback to random")
            
        lines.append("    ")
        return lines

    def _generate_monitors_code(self, sim_params):
        """Generate monitoring code."""
        num_neurons = sim_params.get("num_neurons", 1)
        n_monitor = min(10, num_neurons)

        return [
            "    # Setup monitors",
            "    spike_monitor = SpikeMonitor(neurons)",
            f'    voltage_monitor = StateMonitor(neurons, "v", record=range({n_monitor}))',
            f'    current_monitor = StateMonitor(neurons, "I", record=range({n_monitor}))',
            "    ",
        ]

    def _generate_run_code(self, sim_params):
        """Generate simulation execution code."""
        sim_time = sim_params.get("sim_time", 100)

        return [
            "    # Run simulation",
            f"    simulation_time = {sim_time} * ms",
            '    print(f"Running simulation for {simulation_time}...")',
            "    run(simulation_time)",
            '    print("Simulation completed!")',
            "    ",
        ]

    def _generate_analysis_code(self):
        """Generate results analysis code."""
        return [
            "    # Analyze results",
            '    print(f"Total spikes: {len(spike_monitor.t)}")',
            "    if len(spike_monitor.t) > 0:",
            "        firing_rate = len(spike_monitor.t) / (simulation_time/second) / len(neurons)",
            '        print(f"Average firing rate: {firing_rate:.2f} Hz")',
            "    ",
            "    return {",
            '        "spike_times": spike_monitor.t/ms,',
            '        "spike_indices": spike_monitor.i,',
            '        "voltage_times": voltage_monitor.t/ms,',
            '        "voltage_traces": voltage_monitor.v/mV,',
            '        "current_times": current_monitor.t/ms,',
            '        "current_traces": current_monitor.I/nA',
            "    }",
            "    ",
        ]

    def _generate_plotting_code(self):
        """Generate plotting code."""
        return [
            "    # Optional: Plot results",
            "    # Uncomment the following to generate plots",
            '    """',
            "    # Spike raster plot",
            "    plt.figure(figsize=(12, 8))",
            "    ",
            "    plt.subplot(2, 1, 1)",
            "    plt.scatter(spike_monitor.t/ms, spike_monitor.i, s=10, alpha=0.7)",
            '    plt.xlabel("Time (ms)")',
            '    plt.ylabel("Neuron index")',
            '    plt.title("Spike Raster Plot")',
            "    plt.grid(True, alpha=0.3)",
            "    ",
            "    # Voltage traces",
            "    plt.subplot(2, 1, 2)",
            "    for i in range(min(3, len(voltage_monitor.v))):",
            '        plt.plot(voltage_monitor.t/ms, voltage_monitor.v[i]/mV, label=f"Neuron {i}")',
            '    plt.xlabel("Time (ms)")',
            '    plt.ylabel("Membrane voltage (mV)")',
            '    plt.title("Membrane Voltage Traces")',
            "    plt.legend()",
            "    plt.grid(True, alpha=0.3)",
            "    ",
            "    plt.tight_layout()",
            "    plt.show()",
            '    """',
            "    ",
        ]

    def _generate_helper_functions(self, params):
        """Generate any helper functions."""
        return [
            'def save_results(results, filename="simulation_results.npz"):',
            '    """Save simulation results to file."""',
            "    np.savez(filename, **results)",
            '    print(f"Results saved to {filename}")',
            "    ",
            "",
        ]

    def _generate_main_execution(self):
        """Generate main execution block."""
        return [
            'if __name__ == "__main__":',
            '    print("Brian2 Neural Network Simulation")',
            '    print("=" * 40)',
            "    ",
            "    try:",
            "        results = run_simulation()",
            '        print("\\nSimulation completed successfully!")',
            "        ",
            "        # Optionally save results",
            "        # save_results(results)",
            "        ",
            "    except ImportError as e:",
            '        print("Error: Brian2 not found. Please install with: pip install brian2")',
            "    except Exception as e:",
            '        print(f"Simulation error: {e}")',
        ]
