"""
Code Generator for Brian2 neural network simulator.
Generates standalone Python scripts from GUI parameters.
"""

from datetime import datetime


class CodeGenerator:
    """Generator for standalone Brian2 simulation code."""

    def __init__(self):
        pass

    def generate_simulation_code(self, params):
        """Generate a complete Brian2 simulation script from parameters."""
        code_lines = []

        # Header and imports
        code_lines.extend(self._generate_header())
        code_lines.extend(self._generate_imports())

        # Main simulation function
        code_lines.extend(self._generate_main_function(params))

        # Helper functions
        code_lines.extend(self._generate_helper_functions(params))

        # Main execution
        code_lines.extend(self._generate_main_execution())

        return "\n".join(code_lines)

    def _generate_header(self):
        """Generate file header with timestamp and description."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return [
            f'"""',
            f"Brian2 Neural Network Simulation",
            f"Generated by brian2sim-gui on {timestamp}",
            f"",
            f"This script reproduces the simulation configured in the GUI.",
            f"Make sure you have Brian2 installed: pip install brian2",
            f'"""',
            f"",
        ]

    def _generate_imports(self):
        """Generate import statements."""
        return [
            "# Import required libraries",
            "from brian2 import *",
            "import matplotlib.pyplot as plt",
            "import numpy as np",
            "from datetime import datetime",
            "",
        ]

    def _generate_main_function(self, params):
        """Generate the main simulation function."""
        lines = [
            "def run_simulation():",
            '    """Run the neural network simulation."""',
            '    print("Starting Brian2 simulation...")',
            "    ",
            "    # Clear any previous Brian2 objects",
            "    start_scope()",
            "    ",
        ]
        # Extract parameters
        sim_params = params.get("simulation", {})
        neuron_params = params.get("neuron_model", {})
        noise_params = params.get("noise", {})
        network_params = params.get("network", {})
        advanced_params = params.get("advanced_network", {})

        # Add parameter comments
        lines.extend(self._generate_parameter_comments(params))

        # Build neurons
        lines.extend(self._generate_neuron_code(sim_params, neuron_params))

        # Add input current
        lines.extend(self._generate_input_current_code(sim_params))

        # Add noise if enabled
        if noise_params.get("enabled", False):
            lines.extend(self._generate_noise_code(noise_params))

        # Add network connections if enabled
        if network_params.get("synaptic_connections", False):
            lines.extend(self._generate_network_code(network_params, advanced_params, sim_params))

        # Setup monitors
        lines.extend(self._generate_monitors_code(sim_params))

        # Run simulation
        lines.extend(self._generate_run_code(sim_params))

        # Analyze results
        lines.extend(self._generate_analysis_code())

        # Plot results
        lines.extend(self._generate_plotting_code())

        return lines

    def _generate_parameter_comments(self, params):
        """Generate comments documenting the parameters."""
        lines = ["    # Simulation Parameters:"]

        sim_params = params.get("simulation", {})
        for key, value in sim_params.items():
            lines.append(f"    # {key}: {value}")

        neuron_params = params.get("neuron_model", {})
        if neuron_params:
            lines.append("    # Neuron Model:")
            for key, value in neuron_params.items():
                lines.append(f"    # {key}: {value}")

        lines.append("    ")
        return lines

    def _generate_neuron_code(self, sim_params, neuron_params):
        """Generate neuron group creation code."""
        lines = ["    # Create neuron group"]

        num_neurons = sim_params.get("num_neurons", 1)
        model_type = neuron_params.get("model_key", "lif")

        if model_type == "lif":
            threshold = neuron_params.get("lif_threshold", -50)
            reset = neuron_params.get("lif_reset", -70)
            tau = neuron_params.get("tau_m", 10)
            resistance = neuron_params.get("resistance", 100)

            lines.extend(
                [
                    f"    tau_m = {tau} * ms",
                    f"    R = {resistance} * Mohm",
                    f"    v_threshold = {threshold} * mV",
                    f"    v_reset = {reset} * mV",
                    "    ",
                    '    neuron_eqs = """',
                    "    dv/dt = (-(v - V_rest) + R * I) / tau : volt",
                    "    I : amp",
                    '    """',
                    "    ",
                    f"    neurons = NeuronGroup({num_neurons}, neuron_eqs,",
                    '                          threshold="v > v_threshold",',
                    '                          reset="v = v_reset")',
                    "    neurons.v = v_reset",
                    "    ",
                ]
            )

        elif model_type == "izhikevich":
            parameters = neuron_params.get("parameters", {})
            a = parameters.get("a", 0.02)
            b = parameters.get("b", 0.2)
            c = parameters.get("c", -65)
            d = parameters.get("d", 8)

            lines.extend(
                [
                    f"    a = {a}",
                    f"    b = {b}",
                    f"    c = {c}",
                    f"    d = {d}",
                    "    ",
                    '    neuron_eqs = """',
                    "    dv/dt = (0.04*v**2 + 5*v + 140 - u + I)/ms : 1",
                    "    du/dt = (a*(b*v - u))/ms : 1",
                    "    I : 1",
                    '    """',
                    "    ",
                    f"    neurons = NeuronGroup({num_neurons}, neuron_eqs,",
                    '                          threshold="v >= 30",',
                    '                          reset="v = c; u += d")',
                    f"    neurons.v = {c}",
                    f"    neurons.u = {b} * {c}",
                    "    ",
                ]
            )

        elif model_type == "adex":
            # Adaptive Exponential Integrate-and-Fire (AdEx)
            parameters = neuron_params.get("parameters", {})
            C = parameters.get("C", 200)
            gL = parameters.get("gL", 10)
            EL = parameters.get("EL", -70)
            VT = parameters.get("VT", -50)
            delT = parameters.get("delT", 2)
            a = parameters.get("a", 2)
            tauw = parameters.get("tauw", 30)
            b = parameters.get("b", 60)

            lines.extend(
                [
                    f"    C = {C} * pF",
                    f"    gL = {gL} * nS",
                    f"    EL = {EL} * mV",
                    f"    VT = {VT} * mV",
                    f"    delT = {delT} * mV",
                    f"    a = {a} * nS",
                    f"    tauw = {tauw} * ms",
                    f"    b = {b} * pA",
                    "    ",
                    '    neuron_eqs = """',
                    "    dv/dt = (gL*(EL - v) + gL*delT*exp((v - VT)/delT) - w + I)/C : volt",
                    "    dw/dt = (a*(v - EL) - w)/tauw : amp",
                    "    I : amp",
                    '    """',
                    "    ",
                    f"    neurons = NeuronGroup({num_neurons}, neuron_eqs,",
                    '                          threshold="v > VT + 5*delT",',
                    '                          reset="v = EL; w += b")',
                    "    neurons.v = EL",
                    "    neurons.w = 0 * pA",
                    "    ",
                ]
            )
        else:
            # Default to simple LIF
            lines.extend(
                [
                    "    # Default LIF model",
                    '    neuron_eqs = "dv/dt = (-v + R*I)/tau : volt"',
                    f"    neurons = NeuronGroup({num_neurons}, neuron_eqs,",
                    '                          threshold="v > -50*mV",',
                    '                          reset="v = -70*mV")',
                    "    neurons.v = -70 * mV",
                    "    ",
                ]
            )

        return lines

    def _generate_input_current_code(self, sim_params):
        """Generate input current code."""
        current_amplitude = sim_params.get("input_current", 0.5)
        current_start = sim_params.get("current_start", 10)
        current_duration = sim_params.get("current_duration", 50)

        return [
            "    # Setup input current",
            f"    I_amplitude = {current_amplitude} * nA",
            f"    I_start = {current_start} * ms",
            f"    I_duration = {current_duration} * ms",
            "    ",
            "    @network_operation(dt=0.1*ms)",
            "    def input_current():",
            "        if I_start <= defaultclock.t < I_start + I_duration:",
            "            neurons.I = I_amplitude",
            "        else:",
            "            neurons.I = 0*nA",
            "    ",
        ]

    def _generate_noise_code(self, noise_params):
        """Generate noise code."""
        intensity = noise_params.get("intensity", 0.1)
        method = noise_params.get("method", "Gaussian")

        lines = [
            "    # Add noise",
            f"    noise_intensity = {intensity} * nA",
        ]

        if method == "Gaussian":
            lines.extend(
                [
                    "    ",
                    "    @network_operation(dt=0.1*ms)",
                    "    def add_noise():",
                    "        neurons.I += noise_intensity * randn(len(neurons))",
                    "    ",
                ]
            )
        elif method == "Ornstein-Uhlenbeck":
            lines.extend(
                [
                    "    # Note: Simplified O-U noise implementation",
                    "    tau_noise = 5 * ms",
                    '    noise_eqs = "dI_noise/dt = -I_noise/tau_noise + sigma*sqrt(2/tau_noise)*xi : amp"',
                    "    # This would require modifying the neuron equations",
                    "    ",
                ]
            )

        return lines

    def _generate_network_code(self, network_params, advanced_params, sim_params):
        """Generate synaptic network code."""
        lines = ["    # Create synaptic connections"]

        if sim_params.get("num_neurons", 1) < 2:
            lines.extend(
                [
                    "    # Note: Network connections require at least 2 neurons",
                    "    # Skipping synapse creation",
                    "    ",
                ]
            )
            return lines

        synaptic_weight = network_params.get("synaptic_weight", 0.1)
        topology = network_params.get("network_topology", "all_to_all")

        lines.extend(
            [
                "    # Synaptic connections",
                f"    w_syn = {synaptic_weight} * nA",
                '    synapses = Synapses(neurons, neurons, "w : amp", on_pre="I += w")',
                "    ",
            ]
        )

        # Connection topology
        if topology == "all_to_all":
            allow_self = network_params.get("allow_self_connections", False)
            if allow_self:
                lines.append("    synapses.connect()  # All-to-all including self-connections")
            else:
                lines.append(
                    '    synapses.connect(condition="i != j")  # All-to-all excluding self'
                )
        elif topology == "one_to_one":
            lines.append('    synapses.connect(j="i+1", skip_if_invalid=True)  # One-to-one chain')
        elif topology == "random":
            prob = network_params.get("connection_probability", 0.3)
            lines.append(f"    synapses.connect(p={prob})  # Random connections")

        lines.extend(
            [
                "    synapses.w = w_syn",
                "    ",
            ]
        )

        # Advanced features
        if advanced_params:
            lines.extend(self._generate_advanced_features_code(advanced_params))

        return lines

    def _generate_advanced_features_code(self, advanced_params):
        """Generate code for advanced network features."""
        lines = []

        # Dale's principle
        if advanced_params.get("dales_principle", {}).get("enabled", False):
            dales_config = advanced_params["dales_principle"]
            ratio = dales_config.get("inhibitory_ratio", 0.2)
            lines.extend(
                [
                    "    # Dale's principle: separate excitatory and inhibitory neurons",
                    f"    inhibitory_ratio = {ratio}",
                    "    n_inhibitory = int(len(neurons) * inhibitory_ratio)",
                    "    if n_inhibitory > 0:",
                    "        # Make connections from last n_inhibitory neurons inhibitory",
                    "        synapses.w[synapses.i >= (len(neurons) - n_inhibitory)] *= -1",
                    "    ",
                ]
            )

        # Synaptic delays
        if advanced_params.get("synaptic_delays", {}).get("enabled", False):
            delay_config = advanced_params["synaptic_delays"]
            delay_type = delay_config.get("delay_type", "fixed")

            if delay_type == "fixed":
                delay = delay_config.get("fixed_delay", 1)
                lines.extend(
                    [
                        "    # Fixed synaptic delays",
                        f"    synapses.delay = {delay} * ms",
                        "    ",
                    ]
                )
            elif delay_type == "uniform":
                min_delay = delay_config.get("min_delay", 0.5)
                max_delay = delay_config.get("max_delay", 2)
                lines.extend(
                    [
                        "    # Uniform random synaptic delays",
                        f'    synapses.delay = "({min_delay} + ({max_delay} - {min_delay}) * rand()) * ms"',
                        "    ",
                    ]
                )

        # STDP (simplified)
        if advanced_params.get("stdp", {}).get("enabled", False):
            lines.extend(
                [
                    "    # STDP (simplified implementation)",
                    "    # Note: Full STDP implementation would require more complex synaptic equations",
                    "    # This is a placeholder for demonstration",
                    "    ",
                ]
            )

        return lines

    def _generate_monitors_code(self, sim_params):
        """Generate monitoring code."""
        num_neurons = sim_params.get("num_neurons", 1)
        n_monitor = min(10, num_neurons)

        return [
            "    # Setup monitors",
            "    spike_monitor = SpikeMonitor(neurons)",
            f'    voltage_monitor = StateMonitor(neurons, "v", record=range({n_monitor}))',
            f'    current_monitor = StateMonitor(neurons, "I", record=range({n_monitor}))',
            "    ",
        ]

    def _generate_run_code(self, sim_params):
        """Generate simulation execution code."""
        sim_time = sim_params.get("sim_time", 100)

        return [
            "    # Run simulation",
            f"    simulation_time = {sim_time} * ms",
            '    print(f"Running simulation for {simulation_time}...")',
            "    run(simulation_time)",
            '    print("Simulation completed!")',
            "    ",
        ]

    def _generate_analysis_code(self):
        """Generate results analysis code."""
        return [
            "    # Analyze results",
            '    print(f"Total spikes: {len(spike_monitor.t)}")',
            "    if len(spike_monitor.t) > 0:",
            "        firing_rate = len(spike_monitor.t) / (simulation_time/second) / len(neurons)",
            '        print(f"Average firing rate: {firing_rate:.2f} Hz")',
            "    ",
            "    return {",
            '        "spike_times": spike_monitor.t/ms,',
            '        "spike_indices": spike_monitor.i,',
            '        "voltage_times": voltage_monitor.t/ms,',
            '        "voltage_traces": voltage_monitor.v/mV,',
            '        "current_times": current_monitor.t/ms,',
            '        "current_traces": current_monitor.I/nA',
            "    }",
            "    ",
        ]

    def _generate_plotting_code(self):
        """Generate plotting code."""
        return [
            "    # Optional: Plot results",
            "    # Uncomment the following to generate plots",
            '    """',
            "    # Spike raster plot",
            "    plt.figure(figsize=(12, 8))",
            "    ",
            "    plt.subplot(2, 1, 1)",
            "    plt.scatter(spike_monitor.t/ms, spike_monitor.i, s=10, alpha=0.7)",
            '    plt.xlabel("Time (ms)")',
            '    plt.ylabel("Neuron index")',
            '    plt.title("Spike Raster Plot")',
            "    plt.grid(True, alpha=0.3)",
            "    ",
            "    # Voltage traces",
            "    plt.subplot(2, 1, 2)",
            "    for i in range(min(3, len(voltage_monitor.v))):",
            '        plt.plot(voltage_monitor.t/ms, voltage_monitor.v[i]/mV, label=f"Neuron {i}")',
            '    plt.xlabel("Time (ms)")',
            '    plt.ylabel("Membrane voltage (mV)")',
            '    plt.title("Membrane Voltage Traces")',
            "    plt.legend()",
            "    plt.grid(True, alpha=0.3)",
            "    ",
            "    plt.tight_layout()",
            "    plt.show()",
            '    """',
            "    ",
        ]

    def _generate_helper_functions(self, params):
        """Generate any helper functions."""
        return [
            'def save_results(results, filename="simulation_results.npz"):',
            '    """Save simulation results to file."""',
            "    np.savez(filename, **results)",
            '    print(f"Results saved to {filename}")',
            "    ",
            "",
        ]

    def _generate_main_execution(self):
        """Generate main execution block."""
        return [
            'if __name__ == "__main__":',
            '    print("Brian2 Neural Network Simulation")',
            '    print("=" * 40)',
            "    ",
            "    try:",
            "        results = run_simulation()",
            '        print("\\nSimulation completed successfully!")',
            "        ",
            "        # Optionally save results",
            "        # save_results(results)",
            "        ",
            "    except ImportError as e:",
            '        print("Error: Brian2 not found. Please install with: pip install brian2")',
            "    except Exception as e:",
            '        print(f"Simulation error: {e}")',
        ]
